<?php

require "../../mpgClasses.php";

/******************************* Request Variables ********************************/

$store_id='monca03650';
$api_token='7Yw0MPTlhjBRcZiE6837';

/****************************** Transactional Variables ***************************/

$type='cavv_preauth';
$order_id='ord-'.date("dmy-G:i:s");
$cust_id='CUST887763';
$amount='4840.00';
$pan='5454545454545454';
$expiry_date='2212';
$cavv='AAABBJg0VhI0VniQEjRWAAAAAAA=';
$crypt_type = '7';
$wallet_indicator = "APP";
$dynamic_descriptor='123456';

// TrId and TokenCryptogram are optional, refer documentation for more details.
$tr_id = '50189815682';
$token_cryptogram = 'APmbM/411e0uAAH+s6xMAAADFA==';

/*************************** Transaction Associative Array ************************/

$txnArray=array(
	'type'=>$type,
	'order_id'=>$order_id,
	'cust_id'=>$cust_id,
	'amount'=>$amount,
	'pan'=>$pan,
	'expdate'=>$expiry_date,
	'cavv'=>$cavv,
	'crypt_type'=>$crypt_type, //mandatory for AMEX only
	//'wallet_indicator'=>$wallet_indicator, //set only for wallet transactions. e.g. APPLE PAY
	//'network'=> "Interac", //set only for Interac e-commerce
	//'data_type'=> "3DSecure", //set only for Interac e-commerce
	'dynamic_descriptor'=>$dynamic_descriptor,
	'threeds_version' => '2', //Mandatory for 3DS Version 2.0+
	'threeds_server_trans_id' => 'e11d4985-8d25-40ed-99d6-c3803fe5e68f' //Mandatory for 3DS Version 2.0+ - obtained from MpiCavvLookup or MpiThreeDSAuthentication
	//,'cm_id' => '8nAK8712sGaAkls56' //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant
	//,'ds_trans_id' => '12345' //Optional - to be used only if you are using 3rd party 3ds 2.0 service
	//,'tr_id' => $tr_id
	//,'token_cryptogram' => $token_cryptogram
);

/****************************** Transaction Object *******************************/

$mpgTxn = new mpgTransaction($txnArray);

/******************* Credential on File **********************************/

$cof = new CofInfo();
$cof->setPaymentIndicator("U");
$cof->setPaymentInformation("2");
$cof->setIssuerId("139X3130ASCXAS9");

$mpgTxn->setCofInfo($cof);

/******************************* Request Object **********************************/

$mpgRequest = new mpgRequest($mpgTxn);
$mpgRequest->setProcCountryCode("CA"); //"US" for sending transaction to US environment
$mpgRequest->setTestMode(true); //false or comment out this line for production transactions

/****************************** HTTPS Post Object *******************************/

$mpgHttpPost  =new mpgHttpsPost($store_id,$api_token,$mpgRequest);

/************************************ Response **********************************/

$mpgResponse=$mpgHttpPost->getMpgResponse();

print("\nCardType = " . $mpgResponse->getCardType());
print("\nTransAmount = " . $mpgResponse->getTransAmount());
print("\nTxnNumber = " . $mpgResponse->getTxnNumber());
print("\nReceiptId = " . $mpgResponse->getReceiptId());
print("\nTransType = " . $mpgResponse->getTransType());
print("\nReferenceNum = " . $mpgResponse->getReferenceNum());
print("\nResponseCode = " . $mpgResponse->getResponseCode());
print("\nISO = " . $mpgResponse->getISO());
print("\nMessage = " . $mpgResponse->getMessage());
print("\nAuthCode = " . $mpgResponse->getAuthCode());
print("\nComplete = " . $mpgResponse->getComplete());
print("\nTransDate = " . $mpgResponse->getTransDate());
print("\nTransTime = " . $mpgResponse->getTransTime());
print("\nTicket = " . $mpgResponse->getTicket());
print("\nTimedOut = " . $mpgResponse->getTimedOut());
print("\nCavvResultCode = " . $mpgResponse->getCavvResultCode());
print("\nIssuerId = " . $mpgResponse->getIssuerId());
print("\nThreeDSVersion = " . $mpgResponse->getThreeDSVersion());
print("\nSourcePanLast4 = " . $mpgResponse->getSourcePanLast4());
print("\nAdviceCode = " . $mpgResponse->getAdviceCode());

?>

