<?php

require "../../mpgClasses.php";

/**************************** Request Variables *******************************/

$store_id='monca03650';
$api_token='7Yw0MPTlhjBRcZiE6837';

/************************* Transactional Variables ****************************/

$type='purchase';
$order_id='Test'.date("dmy-G:i:s");
$amount='10.00';
$pan='4242424242424242';
$expdate='2212';
$crypt='7';
$dynamic_descriptor='123';
$status_check = 'false';

$consent_id = '079070e7-125d-47ca-87ee-a667d2e656f4';
$cryptogram = 'eyJraWQiOiJpZGlyZWN0LXRva2VuLWp3cy0wMDEiLCJhbGciOiJFUzI1NiJ9..aSJxeA1nCiRLFgeMgENXQWNdBVu0iZEdejBP4K6J__kN_448ysHzr0LyWi3W0Eg8nRVDen5pHZVH5ZtXpyDkjQ';
$cryptogram_expiry = '2025-02-05T16:48:49.000Z';
$payment_method = 'BANK_ACCOUNT_CHEQUING';
$channel = 'DESKTOP_WEB';

// TrId and TokenCryptogram are optional, refer documentation for more details.
$tr_id = '50189815682';
$token_cryptogram = 'APmbM/411e0uAAH+s6xMAAADFA==';

/*********************** Transactional Associative Array **********************/

$txnArray=array('type'=>$type,
     		    'order_id'=>$order_id,
    		    'amount'=>$amount,
   			    'pan'=>$pan,
   			    'expdate'=>$expdate,
   			    'crypt_type'=>$crypt
   			    //'dynamic_descriptor'=>$dynamic_descriptor
				//,'wallet_indicator' => '' //Refer to documentation for details
				//,'cm_id' => '8nAK8712sGaAkls56' //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant
				//,'tr_id' => $tr_id
				//,'token_cryptogram' => $token_cryptogram
   		       );

/**************************** Transaction Object *****************************/

$mpgTxn = new mpgTransaction($txnArray);

/******************* Credential on File **********************************/

$cof = new CofInfo();
$cof->setPaymentIndicator("U");
$cof->setPaymentInformation("2");
$cof->setIssuerId("139X3130ASCXAS9");

$mpgTxn->setCofInfo($cof);

/******************* PBB Info **********************************/

$pbb_info = new PbbInfo();
$pbb_info->setConsentId($consent_id);
$pbb_info->setCryptogram($cryptogram);
$pbb_info->setCryptogramExpiry($cryptogram_expiry);
$pbb_info->setPaymentMethod($payment_method);
$pbb_info->setChannel($channel);

$mpgTxn->setPbbInfo($pbb_info);


/******************* Installment Info *OPTIONAL* **********************************/

$installmentInfo = new InstallmentInfo();
$installmentInfo->setPlanId("ae859ef1-eb91-b708-8b80-1dd481746401");
$installmentInfo->setPlanIdRef("0000000065");
$installmentInfo->setTacVersion("2");

//$mpgTxn->setInstallmentInfo($installmentInfo);

/******************* Surcharge Info *OPTIONAL* **********************************/
$surchargeInfo = new SurchargeInfo();
$surchargeInfo->setSurchargeAmount("0.01");
//$mpgTxn->setSurchargeInfo($surchargeInfo);


/****************************** Request Object *******************************/

$mpgRequest = new mpgRequest($mpgTxn);
$mpgRequest->setProcCountryCode("CA"); //"US" for sending transaction to US environment
$mpgRequest->setTestMode(true); //false or comment out this line for production transactions

/***************************** HTTPS Post Object *****************************/

/* Status Check Example
$mpgHttpPost  =new mpgHttpsPostStatus($store_id,$api_token,$status_check,$mpgRequest);
*/

$mpgHttpPost = new mpgHttpsPost($store_id,$api_token,$mpgRequest);

/******************************* Response ************************************/

$mpgResponse=$mpgHttpPost->getMpgResponse();

print("\nCardType = " . $mpgResponse->getCardType());
print("\nTransAmount = " . $mpgResponse->getTransAmount());
print("\nTxnNumber = " . $mpgResponse->getTxnNumber());
print("\nReceiptId = " . $mpgResponse->getReceiptId());
print("\nTransType = " . $mpgResponse->getTransType());
print("\nReferenceNum = " . $mpgResponse->getReferenceNum());
print("\nResponseCode = " . $mpgResponse->getResponseCode());
print("\nISO = " . $mpgResponse->getISO());
print("\nMessage = " . $mpgResponse->getMessage());
print("\nIsVisaDebit = " . $mpgResponse->getIsVisaDebit());
print("\nAuthCode = " . $mpgResponse->getAuthCode());
print("\nComplete = " . $mpgResponse->getComplete());
print("\nTransDate = " . $mpgResponse->getTransDate());
print("\nTransTime = " . $mpgResponse->getTransTime());
print("\nTicket = " . $mpgResponse->getTicket());
print("\nTimedOut = " . $mpgResponse->getTimedOut());
print("\nStatusCode = " . $mpgResponse->getStatusCode());
print("\nStatusMessage = " . $mpgResponse->getStatusMessage());
print("\nHostId = " . $mpgResponse->getHostId());
print("\nIssuerId = " . $mpgResponse->getIssuerId());
print("\nSourcePanLast4 = " . $mpgResponse->getSourcePanLast4());
print("\nAdviceCode = " . $mpgResponse->getAdviceCode());


// $installmentResults = $mpgResponse->getInstallmentResults();

// print("\nPlanId = " . $installmentResults->getPlanId());
// print("\nPlanIDRef = " . $installmentResults->getPlanIDRef());
// print("\nTacVersion = " . $installmentResults->getTacVersion());
// print("\nPlanAcceptanceId = " . $installmentResults->getPlanAcceptanceId());
// print("\nPlanStatus = " . $installmentResults->getPlanStatus()); 
// print("\nPlanResponse = " . $installmentResults->getPlanResponse());

?>

